version: 2
jobs:
  build:
    working_directory: ~/cc-project
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "using yarn and installing dependencies"
          command: |
            sudo npm install -g yarn
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "tslint and jest"
          command: |
            yarn lint
            yarn test:coverage
            yarn coveralls

workflows:
  version: 2
  ci_cc_project:
    jobs:
      - node9
        filters:
          branches:
            only:
              - dev
              - master
              - /tag-.*/
